sudo: required
language: node_js
node_js:
  - "lts/*"
cache:
  yarn: true
  directories:
    - "node_modules"

branches:
  only:
    - master
    - develop

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$PATH"

before_deploy:
  - yarn run docs:build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: 'gh-pages'
  on:
    branch: master